name: MyFirstWorkflow

on:
  push:
    branches: [ main ]

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Say Hello
        run: |
          echo "Workflow pornit cu succes!"
      - name: say hello again
        run: |
          echo "Aici este al doile step in care salutam"
