name: MyFirstWorkflow

on:
  push:
    branches: [ main ]

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        use: actions/checkout@v3
      - name: Say Hello
        run: |
          echo "Workflow pornit cu succes!"
